---
# tasks file for ansible-role-thumbor
- name: update apt
  apt: update_cache=yes

- name: install thumbor deps
  apt: pkg={{item}}
  with_items:
    - python-pip
    - python-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - python-numpy
    - python-opencv
    - libopencv-dev
    - libjpeg-de
    - libpng-dev
    - libx264-dev
    - libass-dev
    - libvpx1
    - libvpx-dev
    - libwebp-dev
    - webp
    - gifsicle
    - libgif-dev