---
# tasks file for ansible-role-thumbor
- name: create thumbor group
  group:
    name={{ thumbor_group }}
    system=yes
    state=present

- name: create thumbor user
  user:
    name={{ thumbor_user }}
    group={{ thumbor_group }}
    home={{ thumbor_home }}
    system=yes
    state=present

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install thumbor deps
  apt: pkg={{item}}
  with_items:
    - supervisor
    - python-pip
    - python-dev
    - python-pycurl
    - python-numpy
    - python-opencv
    - python-scipy
    - python-pyexiv2
    - cython
    - libssl-dev
    - libcurl4-openssl-dev
    - libopencv-dev
    - libjpeg-dev
    - libpng-dev
    - libx264-dev
    - libass-dev
    - libvpx1
    - libvpx-dev
    - libwebp-dev
    - webp
    - gifsicle
    - libgif-dev

- name: install thumbor
  pip: name=thumbor

- name: create thumbor config dir
  file:
    path={{thumbor_config_dir}}
    owner={{ thumbor_user }}
    group={{ thumbor_group }}
    mode=0755
    state=directory

- name: configure thumbor
  template:
    src=thumbor.conf.j2
    dest="{{ thumbor_config_dir }}/thumbor.conf"
    owner={{ thumbor_user }}
    group={{ thumbor_group }}
    mode=0755
  notify:
    - restart thumbor

- name: copy thumbor key
  template:
    src=thumbor.key.j2
    dest="{{ thumbor_config_dir }}/thumbor.key"
    owner={{ thumbor_user }}
    group={{ thumbor_group }}
    mode=0755

- name: create folders
  file:
    path={{item}}
    state=directory
    owner={{ thumbor_user }}
    group={{ thumbor_group }}
    mode=0775
  with_items:
    - "{{thumbor_log_dir}}"
    - "{{thumbor_storage_root_path}}"
    - "{{thumbor_result_storage_file_storage_root_path}}"
    - "{{thumbor_loader_root_path}}"

- name: Make sure supervisord service is enabled to start on boot
  service:
    name: supervisor
    enabled: yes
    state: started

- name: Copy supervisord config file (which spawns the thumbor processes)
  template:
    src: supervisor.thumbor.conf.j2
    dest: "/etc/supervisor/conf.d/thumbor.conf"
  notify:
    - restart thumbor
