---
# tasks file for ansible-role-thumbor
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: create thumbor group
  group:
    name: "{{ thumbor_group }}"
    system: yes
    state: present

- name: create thumbor user
  user:
    name: "{{ thumbor_user }}"
    group: "{{ thumbor_group }}"
    home: "{{ thumbor_home }}"
    system: yes
    state: present

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install thumbor deps
  apt: pkg={{item}}
  with_items: "{{ thumbor_packages }}"


- name: install thumbor
  pip: name=thumbor

- name: create thumbor config dir
  file:
    path: "{{thumbor_config_dir}}"
    state: directory

- name: configure thumbor
  template:
    src: thumbor.conf.j2
    dest: "{{ thumbor_config_dir }}/thumbor.conf"
  notify:
    - restart thumbor

- name: copy thumbor key
  template:
    src: thumbor.key.j2
    dest: "{{ thumbor_config_dir }}/thumbor.key"

- name: create folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ thumbor_user }}"
    group: "{{ thumbor_group }}"
    mode: 0755
  with_items:
    - "{{thumbor_log_dir}}"
    - "{{thumbor_storage_root_path}}"
    - "{{thumbor_result_storage_file_storage_root_path}}"
    - "{{thumbor_loader_root_path}}"

- name: check logrotate
  stat: path=/etc/logrotate.d
  register: logrotate
  when: thumbor_add_logrotate

- name: setup logrotate config
  template:
    src: thumbor.logrotate
    dest: "/etc/logrotate.d/thumbor"
  when: thumbor_add_logrotate and logrotate.stat.isdir is defined and logrotate.stat.isdir

- name: Copy supervisord config file (which spawns the thumbor processes)
  template:
    src: supervisor.thumbor.conf.j2
    dest: "/etc/supervisor/conf.d/thumbor.conf"
  notify:
    - restart thumbor

- name: Make sure supervisord service is enabled to start on boot
  service:
    name: supervisor
    enabled: yes
    state: started
